version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    container_name: nest-docker-postgres
    # volumes:
    #   - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - nestjs-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-app
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - nestjs-net

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-docker-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - db
    networks:
      - nestjs-net

networks:
  nestjs-net:
    driver: bridge